version: 0.2

phases:
  pre_build:
    commands:
      - apt-get update
      - env DEBIAN_FRONTEND=noninteractive apt-get -y install build-essential cmake git libssl-dev libcurl4-openssl-dev zlib1g-dev awscli valgrind
  build:
    commands:
      - build-tools/bin/codebuild-test.sh

