# Configuration for the "CBMC Proofs" CI
#
# What the CI should do, depending on what branch the pull request
# targets. This is a list of branch names (or '*' as a wildcard that
# matches all branches), with an associated action. Actions can be:
#
#   name: run-proofs
#
#   or
#
#   name: skip
#   message: "A message to post to GitHub about why the branch was skipped"
#   status: <"success"|"failure">
#           (whether the GitHub status check should succeed or fail)
#
behaviors:

  - target-branches:
    - '*'
    action:
      name: run-proofs


checkout-script:
  # If this is the private version of the repository, we need to pull in
  # the private versions of the submodules.
  # Temporarily disabling this since it's not working yet 
  #- "echo Originating GitHub repository: ${GITHUB_REPOSITORY}"
  #- ./switch-private-submodules --verbose private
  - git submodule update --init --recursive --checkout
