name: test-clang-format

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    runs-on: codebuild-CryptoToolsCI-linux-aws-encryption-sdk-c-${{ github.run_id }}-${{ github.run_attempt }}

    steps:
    - uses: actions/checkout@v4
    - uses: DoozyX/clang-format-lint-action@v0.17
      with:
        source: '.'
        exclude: 'docker-images,doxygen,examples,testing-resources'
        extensions: 'h,c,cpp'
        clangFormatVersion: 9
